baseURL = 'https://cloud-fundis.github.io'
languageCode = 'en-us'
title = 'Cloud Fundis Brightspark Documentation'
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false